apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        app: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: yellow1238/frontend:v1
        resources:
          requests:
            memory: "120Mi"
            cpu: "100m"
            # limits is greater than or equal to requests 
          limits:
            memory: "120Mi"
            cpu: "100m" 
        ports:
        - containerPort: 80

          
---
# if anybod wants to connect backend from outside of cluster
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
   app: frontend
   project: expense
   tier: web
  ports:
  - name: frontend-port
    port: 80 # service port
    protocol: TCP
    targetPort: 80 # container port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15 # usually 75 in real environment
  