apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs
provisioner: ebs.csi.aws.com
reclaimPolicy: retain
volumeBindingMode: WaitForFirstConsumer # storageclass will be created volume when pod is getting created