apiVersion: v1
kind: Service
metadata:
  name: mysql-headless 
  namespace: expense
spec:
  clusterIP: None # for headless service there is no cluster IP
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
      port: 3306
      protocol: TCP
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: nginx 
  namespace: expense
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
      port: 3306
      protocol: TCP
      targetPort: 3306 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db      
  serviceName: "mysql-headless" # It is headless service should be mentioned for statefulset
  replicas: 2 # 
  template:
      labels:
        project: expense
        component: mysql
        tier: db    
  spec:
      containers:
      - name: mysql
        image: yellow1238/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # This is pvc definition, directly mentioned here
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi