---
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  ports:
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    component: mysql
    project: expense
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: expense
spec:
  ports:
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    component: mysql
    project: expense
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  serviceName: mysql-headless
  spec:
    containers:
      - image: yellow1238/mysql:v1
        name: mysql
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql
  template:
    labels:
      component: mysql
      project: expense
      tier: db
    # This is pvc definition, directly mentioned here
volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: expense-ebs